package deployer

// OPDeploymentState represents the OP Stack deployment state from state.json
// This is the raw state file generated by op-deployer
type OPDeploymentState struct {
	ImplementationsDeployment ImplementationsDeployment `json:"implementationsDeployment"`
	OpChainDeployments        []OpChainDeployment       `json:"opChainDeployments"`
}

// ImplementationsDeployment represents shared implementation contracts
type ImplementationsDeployment struct {
	DisputeGameFactoryImplAddress string `json:"DisputeGameFactoryImpl"`
}

// OpChainDeployment represents per-chain L1 contracts
type OpChainDeployment struct {
	ID                      string     `json:"id"`
	StartBlock              StartBlock `json:"startBlock"`
	SystemConfigProxy       string     `json:"SystemConfigProxy"`
	DisputeGameFactoryProxy string     `json:"DisputeGameFactoryProxy"`
}

// StartBlock represents the L1 block where the rollup starts
type StartBlock struct {
	Hash   string `json:"hash"`
	Number string `json:"number"`
}
