package deployer

import (
	"bytes"
	"encoding/json"
)

// OPDeploymentState represents the OP Stack deployment state from state.json
// This is the raw state file generated by op-deployer
type OPDeploymentState struct {
	AppliedIntent             json.RawMessage           `json:"appliedIntent"`
	SuperchainContracts       SuperchainContracts       `json:"superchainContracts"`
	ImplementationsDeployment ImplementationsDeployment `json:"implementationsDeployment"`
	OpChainDeployments        []OpChainDeployment       `json:"opChainDeployments"`
}

// HasIncompleteProgress reports whether apply started mutating state but never
// reached a full successful apply.
func (s *OPDeploymentState) HasIncompleteProgress() bool {
	if s == nil {
		return false
	}

	return rawMessageIsNull(s.AppliedIntent) && s.hasProgress()
}

func (s *OPDeploymentState) hasProgress() bool {
	return s.SuperchainContracts.hasAny() ||
		s.ImplementationsDeployment.hasAny() ||
		len(s.OpChainDeployments) > 0
}

// SuperchainContracts represents shared superchain proxy addresses.
type SuperchainContracts struct {
	SuperchainProxyAdminImpl string `json:"SuperchainProxyAdminImpl"`
	SuperchainConfigProxy    string `json:"SuperchainConfigProxy"`
	ProtocolVersionsProxy    string `json:"ProtocolVersionsProxy"`
}

func (s SuperchainContracts) hasAny() bool {
	return s.SuperchainProxyAdminImpl != "" ||
		s.SuperchainConfigProxy != "" ||
		s.ProtocolVersionsProxy != ""
}

// ImplementationsDeployment represents shared implementation contracts
type ImplementationsDeployment struct {
	DisputeGameFactoryImplAddress string `json:"DisputeGameFactoryImpl"`
}

func (i ImplementationsDeployment) hasAny() bool {
	return i.DisputeGameFactoryImplAddress != ""
}

func rawMessageIsNull(msg json.RawMessage) bool {
	return len(msg) == 0 || bytes.Equal(bytes.TrimSpace(msg), []byte("null"))
}

// OpChainDeployment represents per-chain L1 contracts
type OpChainDeployment struct {
	ID                      string     `json:"id"`
	StartBlock              StartBlock `json:"startBlock"`
	AltDAChallengeProxy        string     `json:"AltDAChallengeProxy"`
	AltDAChallengeImpl         string     `json:"AltDAChallengeImpl"`
	SystemConfigProxy          string     `json:"SystemConfigProxy"`
	DisputeGameFactoryProxy    string     `json:"DisputeGameFactoryProxy"`
	AnchorStateRegistryProxy   string     `json:"AnchorStateRegistryProxy"`
}

// StartBlock represents the L1 block where the rollup starts
type StartBlock struct {
	Hash   string `json:"hash"`
	Number string `json:"number"`
}
